### ISSUE TITLE
Interval Stops when API throw Error

### ISSUE THREAD

**Issue by puneet0911** [andyfleming/interval-promise#24]
I am getting the rate from the API and if the side is giving the Error then the Interval stops.
It should work.
this function is defined in the system core file.
```
function xmlApiHandler(obj) {
	let xmlObject = xmlBuilder(obj);
	return request({
		               url    : process.env.URL,
		               method : "POST",
		               headers: { "Content-Type": "application/xml" },
		               body   : xmlObject
	               })
		.then(function (result) {			
			return xmlParser(result);
		})
		.catch(function (err) {			
			throw err;
		});
}
```
API can In this function in the reciever file
```
async function rateUpdate(currency) {	
	try {
		let rateStatus = await systemCore.xmlApiHandler(currency);
	} catch (e) {		
		await systemCore.catchErrorRequest({"file":"receiver", "State":"Getting inside the Rate interval", "error" : e.error, "error_stack" : e.stack, "status" : e.statusCode}); // its going here
	}	
};
```
Now We are using in the interval file
```
const interval        = require('interval-promise');
rateUpdateInterval   = 30000;
interval(async function () {
        await recieverJobs.rateUpdate();
    }, rateUpdateInterval);
```

Once the Server will give any error interval polling stops.

> **Can you please let me know how to resolve this?**

**Comment by hasezoey** [comment]
did you already try `stopOnError: false`?
https://github.com/andyfleming/interval-promise#arguments

could you describe what `catchErrorRequest` does? maybe it throws and so ends the iteration?

**Comment by puneet0911** [comment]
No, I did not try `stopOnError: false`. Now I will check Thank you.
Error is not always showing it's only showing sometimes. 
Here is the error :- 
```
Error: getaddrinfo EBUSY xxxx.xxxx.com\n    at new RequestError (/home/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/home/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/home/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/home/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:203:13)\n    at
at Request.onRequestError (/home/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:6571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6571) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hasezoey** [comment]
it seems like the error is internal from `request-promise`, but not catched internally, so it is thrown as an "unhandled Promise Rejection"

PS: could you try 
```ts
// make the function it is in async
return xmlParser(await request({
		               url    : process.env.URL,
		               method : "POST",
		               headers: { "Content-Type": "application/xml" },
		               body   : xmlObject
	               }))
```

**Comment by andyfleming** [comment]
Closing this. Please re-open (or open a new issue) if there's a bug or feature request.
